### PR TITLE
Fix stopping animation when view is not visible for Robolectric/Espre…

### LINKED ISSUE #21: Causes robolectric unable to proceed
Hi, I was using this library and robolectric (3.0-rc3) for unit test. I found that `circularProgressView.startAnimation()` will prevent Robolectric from proceeding.

```Java
public class MainActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        CircularProgressView progressView = (CircularProgressView) findViewById(R.id.progress_view);
        progressView.startAnimation();
    }
}

@RunWith(RobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 21)
public class MainActivityTest {
    @Test
    public void testMainActivity() {
        MainActivity mainActivity = Robolectric.setupActivity(MainActivity.class);
        Assert.assertNotNull(mainActivity);
    }
}
```

The program will stuck in `setupActivity()` and the assertion will never be reached. And if I comment out `progressView.startAnimation();`, then everything works fine. I don't know if its a problem of this library or of Robolectric, but would you take a look at this?

### PR DESCRIPTION
**Pull request by lukaszkalnik**
Resolves #21

### CODE REVIEW

**Comment by rahatarmanahmed** [comment]
Since `cancel()` is a public method, can you rename it to `stopAnimation()`, which is more descriptive and consistent with the other corresponding public methods.

And if you could update the `README.md` with the new method, that would be very helpful!

Other than those two nitpicks, looks good!

**Comment by lukaszkalnik** [comment]
Ok, I also moved the `stopAnimation()` method right after `startAnimation()` and `resetAnimation()` to keep them together.

**Comment by rahatarmanahmed** [comment]
Ah, one more small bug I noticed. If you do `progressView.setVisibility(View.VISIBLE)` while the view is already set to `VISIBLE`, it will reset the animation.

**Comment by lukaszkalnik** [comment]
Right, thanks for pointing that one out!

**Comment by lukaszkalnik** [comment]
Cool, thanks! :)

**Comment by rahatarmanahmed** [comment]
Appreciate the PR, thanks for fixing all the little things as well!

**Pull request merged**
