### PR TITLE
Added 'startAngle' as XML parameter for determinate progress use

### PR DESCRIPTION
**Pull request by saadfarooq**
This is useful when using the ProgressView in determinate mode where we want to show percent progress towards a goal (e.g. 80% complete) and we want to start the progress bar at a specific angle instead of the default 0.

### CODE REVIEW

**Comment by rahatarmanahmed** [comment]
Well, looks a lot better than what #2 tried to do. I'll confirm and merge sometime this weekend.

**Comment by rahatarmanahmed** [comment]
Also please update the documentation in README.md

**Comment by saadfarooq** [comment]
Updated README.md

**Comment by rahatarmanahmed** [comment]
Just got a moment to look at this, it doesn't work. Please don't make a PR unless you've tested the changes.

[This line](https://github.com/rahatarmanahmed/CircularProgressView/blob/master/circularprogressview/src/main/java/com/github/rahatarmanahmed/cpv/CircularProgressView.java#L338) is where the startAngle should be set. Admittedly, i guess it doesn't make sense to name it startAngle there and use the same variable later, even when i'm not "starting". So what you should probably do is rename the old startAngle to angle, and initialize it at that line to your startAngle. Also change the default to -90 or 270.

**Comment by saadfarooq** [comment]
Really ? How are you testing ? The intended usage is to have
`        app:cpv_indeterminate="false"
        app:cpv_startAngle="-90"`
and then `setProgress` in your code as needed.

**Comment by rahatarmanahmed** [comment]
I'm testing using the example application in this repo, with some changes like adding cpv_startAngle. I saw that it started the swoop animation from the same angle as before, and stayed at the same position after it settled. Actually, here's what I put

    <com.github.rahatarmanahmed.cpv.CircularProgressView
        android:id="@+id/progress_view"
        android:layout_width="40dp"
        android:layout_height="40dp"
        android:layout_centerHorizontal="true"
        android:layout_centerVertical="true"
        android:padding="0dp"
        app:cpv_animAutostart="false"
        app:cpv_indeterminate="false"
        app:cpv_startAngle="45"
        app:cpv_thickness="4dp" />

But you don't need to test it to see that it won't work. when `resetAnimation()` is called to start the animation, it initializes `startAngle` to -90.

**Comment by saadfarooq** [comment]
The startAngle parameter is intended to be the angle at which progress starts in determinant progress mode. It's not the swoop startAngle but the canvas startAngle. It works fine in determinant progress mode but not if you are switching between indeterminate and determinate progress modes. I added an example to the PR.
Even if you wanted this to also determine the swoop startAngle (which shouldn't be hard if the swoop is guaranteed to be 360 degrees), the line you pointed out is completely irrelevant. That variable is not even used in determining the animator and is overridden as soon as the first animation callback comes through so it doesn't matter what it's value is at this point. I'm not even sure why you have it there.

**Comment by rahatarmanahmed** [comment]
Ah, I understand now, you're not using the determinate animation. I apologize for calling you out earlier (had issues with PRs that were never tested before).

Still, it's inconsistent to have a startAngle option that doesn't work if you use the animation, and I'd like for it to work in that case as well. The swoop is 360 degrees so it is simple, and there's no reason not to support that, so I'd appreciate it if you'd add that in. (Also remove your example commit).

**Comment by saadfarooq** [comment]
This is the best I could get it to do. There is a slight jank when starting indeterminate animation that I can't figure out. The rest seems fine.

**Comment by rahatarmanahmed** [comment]
Sorry, this PR slipped between the cracks while I started my new job. Thanks for your contribution!

**Comment by rahatarmanahmed** [comment]
Just released v2.4.0 with this PR, should be available from maven in a few hours

**Pull request merged**
