### PR TITLE
Update to use actual theme's accent color

### PR DESCRIPTION
**Pull request by Kinnonii**
As default Lollipop's ProgressBar uses the theme's accent color if no xml attribute is specified, I've made changes to accord this.

Now, you can specify the color to use in the xml layout, or if you don't do that, it will use the accent color specified in the app theme. If no accent color specified, it will use the parent's accent color.

### CODE REVIEW

**Comment by rahatarmanahmed** [comment]
I'd like there to be a fallback color for anyone not using Lollipop's theme accent. Do that and i'll merge this. Also, will this work with AppCompat?

**Comment by Kinnonii** [comment]
Yes, I tried it with themes that extends from Theme.AppCompat (which extends from Theme.Material) and it has a default accentColor for use when the user doesn't specify it. So this would work on any device that supports AppCompat v7 support library (actually Api 7+). Tried it on 4.0.3+

**Comment by rahatarmanahmed** [comment]
Okay good, but I still don't want AppCompat to be a requirement so could
you keep the default color if the accent color isn't found?

**Comment by Kinnonii** [comment]
Android new project's default theme extends from Theme.AppCompat but I'll give it a look and reply ASAP.

**Comment by rahatarmanahmed** [comment]
I've had an issue complain (incorrectly) about this library depending on
the support library so it seems some people have a concern for this out
there.

**Comment by Kinnonii** [comment]
Hmmmm. Well, the library doesn't depend of the support library but my code needs a theme extending Theme.Material which has the colorAccent attr. The logic tells me that if you want a Material-like behavior, you should inherit Theme.Material (or Theme.AppCompat from the support library) to have a materialized app.

But, my solution would be two classes, one with a default color for non-AppCompat or support library users, and my modified version on the other hand, which automatically takes your accent color. What do you think about it?

**Comment by rahatarmanahmed** [comment]
That's completely unnecessary, according to the [documentation](http://developer.android.com/reference/android/content/res/Resources.Theme.html#resolveAttribute(int, android.util.TypedValue, boolean)) for Themes, resolveAttribute returns false if it doesn't find the attribute. Just check that and apply old code if it doesn't find the accent color.

**Comment by Kinnonii** [comment]
I've already tried that and that's why I've separated into two files. If the attribute doesn't exist on the theme, the compiler throws an error "R.attr.colorAccent not found" and that stuff. I don't know if it's a bug because it should compile and return false.

**Comment by rahatarmanahmed** [comment]
Then try using [getContext().gtResources().getIdentifier(...)](http://developer.android.com/reference/android/content/res/Resources.html#getIdentifier(java.lang.String, java.lang.String, java.lang.String))

**Comment by Kinnonii** [comment]
Done! :)

**Comment by rahatarmanahmed** [comment]
Excellent. If you can do one last thing for me and fix the README and then rebase everything into a single commit so we don't have all those extra commits in the history, i'll test and merge later today.

**Comment by Kinnonii** [comment]
Should I close this pull request and open a new one with only one commit?

**Pull request closed without merging**
